#version 450

// =============================================================================
// WulfNet Engine - Clear Voxel Grid
// =============================================================================

layout(local_size_x = 64) in;

layout(std430, binding = 0) buffer VoxelGrid {
    int voxels[];
};

layout(push_constant) uniform PushConstants {
    uint memoryOffset;
};

void main() {
    voxels[gl_GlobalInvocationID.x + memoryOffset] = 0;
}
